//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AssignedProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssignedProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="installationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="deactivationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="type" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}CodeValueType" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}AssignedProductIdentifierType" maxOccurs="100"/>
 *         &lt;element name="billingAccountIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingAccountIdentifierType" minOccurs="0"/>
 *         &lt;element name="installationPoint" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}InstallationPointType" minOccurs="0"/>
 *         &lt;element name="requestedAction" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}AssignedProductActionType"/>
 *         &lt;element name="serviceIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}ServiceIdentifierType" minOccurs="0"/>
 *         &lt;element name="geographicAddressIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}GeographicAddressIdentifierType" minOccurs="0"/>
 *         &lt;element name="usedAtAddress" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}GeographicAddressIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssignedProductType", propOrder = {
    "installationDate",
    "deactivationDate",
    "type",
    "identifier",
    "billingAccountIdentifier",
    "installationPoint",
    "requestedAction",
    "serviceIdentifier",
    "geographicAddressIdentifier",
    "usedAtAddress"
})
public class AssignedProductType {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar installationDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar deactivationDate;
    protected CodeValueType type;
    @XmlElement(required = true)
    protected List<AssignedProductIdentifierType> identifier;
    protected BillingAccountIdentifierType billingAccountIdentifier;
    protected InstallationPointType installationPoint;
    @XmlElement(required = true)
    protected AssignedProductActionType requestedAction;
    protected ServiceIdentifierType serviceIdentifier;
    protected GeographicAddressIdentifierType geographicAddressIdentifier;
    protected GeographicAddressIdentifierType usedAtAddress;

    /**
     * Gets the value of the installationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInstallationDate() {
        return installationDate;
    }

    /**
     * Sets the value of the installationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInstallationDate(XMLGregorianCalendar value) {
        this.installationDate = value;
    }

    /**
     * Gets the value of the deactivationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeactivationDate() {
        return deactivationDate;
    }

    /**
     * Sets the value of the deactivationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeactivationDate(XMLGregorianCalendar value) {
        this.deactivationDate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setType(CodeValueType value) {
        this.type = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignedProductIdentifierType }
     * 
     * 
     */
    public List<AssignedProductIdentifierType> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<AssignedProductIdentifierType>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the billingAccountIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BillingAccountIdentifierType }
     *     
     */
    public BillingAccountIdentifierType getBillingAccountIdentifier() {
        return billingAccountIdentifier;
    }

    /**
     * Sets the value of the billingAccountIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingAccountIdentifierType }
     *     
     */
    public void setBillingAccountIdentifier(BillingAccountIdentifierType value) {
        this.billingAccountIdentifier = value;
    }

    /**
     * Gets the value of the installationPoint property.
     * 
     * @return
     *     possible object is
     *     {@link InstallationPointType }
     *     
     */
    public InstallationPointType getInstallationPoint() {
        return installationPoint;
    }

    /**
     * Sets the value of the installationPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallationPointType }
     *     
     */
    public void setInstallationPoint(InstallationPointType value) {
        this.installationPoint = value;
    }

    /**
     * Gets the value of the requestedAction property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedProductActionType }
     *     
     */
    public AssignedProductActionType getRequestedAction() {
        return requestedAction;
    }

    /**
     * Sets the value of the requestedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedProductActionType }
     *     
     */
    public void setRequestedAction(AssignedProductActionType value) {
        this.requestedAction = value;
    }

    /**
     * Gets the value of the serviceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceIdentifierType }
     *     
     */
    public ServiceIdentifierType getServiceIdentifier() {
        return serviceIdentifier;
    }

    /**
     * Sets the value of the serviceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceIdentifierType }
     *     
     */
    public void setServiceIdentifier(ServiceIdentifierType value) {
        this.serviceIdentifier = value;
    }

    /**
     * Gets the value of the geographicAddressIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicAddressIdentifierType }
     *     
     */
    public GeographicAddressIdentifierType getGeographicAddressIdentifier() {
        return geographicAddressIdentifier;
    }

    /**
     * Sets the value of the geographicAddressIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicAddressIdentifierType }
     *     
     */
    public void setGeographicAddressIdentifier(GeographicAddressIdentifierType value) {
        this.geographicAddressIdentifier = value;
    }

    /**
     * Gets the value of the usedAtAddress property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicAddressIdentifierType }
     *     
     */
    public GeographicAddressIdentifierType getUsedAtAddress() {
        return usedAtAddress;
    }

    /**
     * Sets the value of the usedAtAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicAddressIdentifierType }
     *     
     */
    public void setUsedAtAddress(GeographicAddressIdentifierType value) {
        this.usedAtAddress = value;
    }

}
