//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillingOrderItemRelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillingOrderItemRelationshipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}CodeValueType"/>
 *         &lt;element name="billingOrderItemIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingOrderItemIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingOrderItemRelationshipType", propOrder = {
    "type",
    "billingOrderItemIdentifier"
})
public class BillingOrderItemRelationshipType {

    @XmlElement(required = true)
    protected CodeValueType type;
    protected BillingOrderItemIdentifierType billingOrderItemIdentifier;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setType(CodeValueType value) {
        this.type = value;
    }

    /**
     * Gets the value of the billingOrderItemIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BillingOrderItemIdentifierType }
     *     
     */
    public BillingOrderItemIdentifierType getBillingOrderItemIdentifier() {
        return billingOrderItemIdentifier;
    }

    /**
     * Sets the value of the billingOrderItemIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingOrderItemIdentifierType }
     *     
     */
    public void setBillingOrderItemIdentifier(BillingOrderItemIdentifierType value) {
        this.billingOrderItemIdentifier = value;
    }

}
