//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillingOrderItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillingOrderItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assignedProductIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}AssignedProductIdentifierType" maxOccurs="100"/>
 *         &lt;element name="comment" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}CommentType" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="charVal" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingOrderItemCharValType" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingOrderItemIdentifierType"/>
 *         &lt;element name="relationship" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingOrderItemRelationshipType" minOccurs="0"/>
 *         &lt;element name="assignedTariffAlterationDiscountIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}AssignedTariffAlterationDiscountIdentifierType" minOccurs="0"/>
 *         &lt;element name="assignedPriceElementGroupIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}AssignedPriceElementGroupIdentifierType" minOccurs="0"/>
 *         &lt;element name="customerAgreementIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}CustomerAgreementIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingOrderItemType", propOrder = {
    "assignedProductIdentifier",
    "comment",
    "charVal",
    "identifier",
    "relationship",
    "assignedTariffAlterationDiscountIdentifier",
    "assignedPriceElementGroupIdentifier",
    "customerAgreementIdentifier"
})
public class BillingOrderItemType {

    @XmlElement(required = true)
    protected List<AssignedProductIdentifierType> assignedProductIdentifier;
    protected List<CommentType> comment;
    protected List<BillingOrderItemCharValType> charVal;
    @XmlElement(required = true)
    protected BillingOrderItemIdentifierType identifier;
    protected BillingOrderItemRelationshipType relationship;
    protected AssignedTariffAlterationDiscountIdentifierType assignedTariffAlterationDiscountIdentifier;
    protected AssignedPriceElementGroupIdentifierType assignedPriceElementGroupIdentifier;
    protected CustomerAgreementIdentifierType customerAgreementIdentifier;

    /**
     * Gets the value of the assignedProductIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignedProductIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignedProductIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignedProductIdentifierType }
     * 
     * 
     */
    public List<AssignedProductIdentifierType> getAssignedProductIdentifier() {
        if (assignedProductIdentifier == null) {
            assignedProductIdentifier = new ArrayList<AssignedProductIdentifierType>();
        }
        return this.assignedProductIdentifier;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentType }
     * 
     * 
     */
    public List<CommentType> getComment() {
        if (comment == null) {
            comment = new ArrayList<CommentType>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the charVal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the charVal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharVal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillingOrderItemCharValType }
     * 
     * 
     */
    public List<BillingOrderItemCharValType> getCharVal() {
        if (charVal == null) {
            charVal = new ArrayList<BillingOrderItemCharValType>();
        }
        return this.charVal;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link BillingOrderItemIdentifierType }
     *     
     */
    public BillingOrderItemIdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingOrderItemIdentifierType }
     *     
     */
    public void setIdentifier(BillingOrderItemIdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link BillingOrderItemRelationshipType }
     *     
     */
    public BillingOrderItemRelationshipType getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingOrderItemRelationshipType }
     *     
     */
    public void setRelationship(BillingOrderItemRelationshipType value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the assignedTariffAlterationDiscountIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedTariffAlterationDiscountIdentifierType }
     *     
     */
    public AssignedTariffAlterationDiscountIdentifierType getAssignedTariffAlterationDiscountIdentifier() {
        return assignedTariffAlterationDiscountIdentifier;
    }

    /**
     * Sets the value of the assignedTariffAlterationDiscountIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedTariffAlterationDiscountIdentifierType }
     *     
     */
    public void setAssignedTariffAlterationDiscountIdentifier(AssignedTariffAlterationDiscountIdentifierType value) {
        this.assignedTariffAlterationDiscountIdentifier = value;
    }

    /**
     * Gets the value of the assignedPriceElementGroupIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedPriceElementGroupIdentifierType }
     *     
     */
    public AssignedPriceElementGroupIdentifierType getAssignedPriceElementGroupIdentifier() {
        return assignedPriceElementGroupIdentifier;
    }

    /**
     * Sets the value of the assignedPriceElementGroupIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedPriceElementGroupIdentifierType }
     *     
     */
    public void setAssignedPriceElementGroupIdentifier(AssignedPriceElementGroupIdentifierType value) {
        this.assignedPriceElementGroupIdentifier = value;
    }

    /**
     * Gets the value of the customerAgreementIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerAgreementIdentifierType }
     *     
     */
    public CustomerAgreementIdentifierType getCustomerAgreementIdentifier() {
        return customerAgreementIdentifier;
    }

    /**
     * Sets the value of the customerAgreementIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerAgreementIdentifierType }
     *     
     */
    public void setCustomerAgreementIdentifier(CustomerAgreementIdentifierType value) {
        this.customerAgreementIdentifier = value;
    }

}
