//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChoiceBusinessInteractionIdentifierInBillingOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChoiceBusinessInteractionIdentifierInBillingOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="customerOrderIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}CustomerOrderIdentifierType"/>
 *         &lt;element name="projectIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}ProjectIdentifierType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChoiceBusinessInteractionIdentifierInBillingOrderType", propOrder = {
    "customerOrderIdentifier",
    "projectIdentifier"
})
public class ChoiceBusinessInteractionIdentifierInBillingOrderType {

    protected CustomerOrderIdentifierType customerOrderIdentifier;
    protected ProjectIdentifierType projectIdentifier;

    /**
     * Gets the value of the customerOrderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerOrderIdentifierType }
     *     
     */
    public CustomerOrderIdentifierType getCustomerOrderIdentifier() {
        return customerOrderIdentifier;
    }

    /**
     * Sets the value of the customerOrderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerOrderIdentifierType }
     *     
     */
    public void setCustomerOrderIdentifier(CustomerOrderIdentifierType value) {
        this.customerOrderIdentifier = value;
    }

    /**
     * Gets the value of the projectIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectIdentifierType }
     *     
     */
    public ProjectIdentifierType getProjectIdentifier() {
        return projectIdentifier;
    }

    /**
     * Sets the value of the projectIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectIdentifierType }
     *     
     */
    public void setProjectIdentifier(ProjectIdentifierType value) {
        this.projectIdentifier = value;
    }

}
