//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstallationPointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstallationPointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}InstallationPointIdentifierType" maxOccurs="100"/>
 *         &lt;element name="geographicLocationIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}ChoiceGeographicLocationIdentifierInProductInventoryType" minOccurs="0"/>
 *         &lt;element name="assignedProduct" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}AssignedProductType" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="geographicAddressIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}GeographicAddressIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstallationPointType", propOrder = {
    "identifier",
    "geographicLocationIdentifier",
    "assignedProduct",
    "geographicAddressIdentifier"
})
public class InstallationPointType {

    @XmlElement(required = true)
    protected List<InstallationPointIdentifierType> identifier;
    protected ChoiceGeographicLocationIdentifierInProductInventoryType geographicLocationIdentifier;
    protected List<AssignedProductType> assignedProduct;
    protected GeographicAddressIdentifierType geographicAddressIdentifier;

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstallationPointIdentifierType }
     * 
     * 
     */
    public List<InstallationPointIdentifierType> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<InstallationPointIdentifierType>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the geographicLocationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ChoiceGeographicLocationIdentifierInProductInventoryType }
     *     
     */
    public ChoiceGeographicLocationIdentifierInProductInventoryType getGeographicLocationIdentifier() {
        return geographicLocationIdentifier;
    }

    /**
     * Sets the value of the geographicLocationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoiceGeographicLocationIdentifierInProductInventoryType }
     *     
     */
    public void setGeographicLocationIdentifier(ChoiceGeographicLocationIdentifierInProductInventoryType value) {
        this.geographicLocationIdentifier = value;
    }

    /**
     * Gets the value of the assignedProduct property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignedProduct property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignedProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignedProductType }
     * 
     * 
     */
    public List<AssignedProductType> getAssignedProduct() {
        if (assignedProduct == null) {
            assignedProduct = new ArrayList<AssignedProductType>();
        }
        return this.assignedProduct;
    }

    /**
     * Gets the value of the geographicAddressIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicAddressIdentifierType }
     *     
     */
    public GeographicAddressIdentifierType getGeographicAddressIdentifier() {
        return geographicAddressIdentifier;
    }

    /**
     * Sets the value of the geographicAddressIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicAddressIdentifierType }
     *     
     */
    public void setGeographicAddressIdentifier(GeographicAddressIdentifierType value) {
        this.geographicAddressIdentifier = value;
    }

}
