//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BillingOrderIdentifierType }
     * 
     */
    public BillingOrderIdentifierType createBillingOrderIdentifierType() {
        return new BillingOrderIdentifierType();
    }

    /**
     * Create an instance of {@link InstallationPointType }
     * 
     */
    public InstallationPointType createInstallationPointType() {
        return new InstallationPointType();
    }

    /**
     * Create an instance of {@link BillingOrderItemType }
     * 
     */
    public BillingOrderItemType createBillingOrderItemType() {
        return new BillingOrderItemType();
    }

    /**
     * Create an instance of {@link IntervalType }
     * 
     */
    public IntervalType createIntervalType() {
        return new IntervalType();
    }

    /**
     * Create an instance of {@link AssignedProductActionType }
     * 
     */
    public AssignedProductActionType createAssignedProductActionType() {
        return new AssignedProductActionType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link BillingOrderItemCharValType }
     * 
     */
    public BillingOrderItemCharValType createBillingOrderItemCharValType() {
        return new BillingOrderItemCharValType();
    }

    /**
     * Create an instance of {@link CharacteristicValueType }
     * 
     */
    public CharacteristicValueType createCharacteristicValueType() {
        return new CharacteristicValueType();
    }

    /**
     * Create an instance of {@link BillingOrderOperationalContextType }
     * 
     */
    public BillingOrderOperationalContextType createBillingOrderOperationalContextType() {
        return new BillingOrderOperationalContextType();
    }

    /**
     * Create an instance of {@link CustomerAgreementIdentifierType }
     * 
     */
    public CustomerAgreementIdentifierType createCustomerAgreementIdentifierType() {
        return new CustomerAgreementIdentifierType();
    }

    /**
     * Create an instance of {@link AssignedTariffAlterationDiscountIdentifierType }
     * 
     */
    public AssignedTariffAlterationDiscountIdentifierType createAssignedTariffAlterationDiscountIdentifierType() {
        return new AssignedTariffAlterationDiscountIdentifierType();
    }

    /**
     * Create an instance of {@link BillingOrderItemRelationshipType }
     * 
     */
    public BillingOrderItemRelationshipType createBillingOrderItemRelationshipType() {
        return new BillingOrderItemRelationshipType();
    }

    /**
     * Create an instance of {@link CodeValueType }
     * 
     */
    public CodeValueType createCodeValueType() {
        return new CodeValueType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link ProjectIdentifierType }
     * 
     */
    public ProjectIdentifierType createProjectIdentifierType() {
        return new ProjectIdentifierType();
    }

    /**
     * Create an instance of {@link BillingOrderRelationshipType }
     * 
     */
    public BillingOrderRelationshipType createBillingOrderRelationshipType() {
        return new BillingOrderRelationshipType();
    }

    /**
     * Create an instance of {@link CustomerIdentifierType }
     * 
     */
    public CustomerIdentifierType createCustomerIdentifierType() {
        return new CustomerIdentifierType();
    }

    /**
     * Create an instance of {@link BillingOrderItemIdentifierType }
     * 
     */
    public BillingOrderItemIdentifierType createBillingOrderItemIdentifierType() {
        return new BillingOrderItemIdentifierType();
    }

    /**
     * Create an instance of {@link CustomerOrderIdentifierType }
     * 
     */
    public CustomerOrderIdentifierType createCustomerOrderIdentifierType() {
        return new CustomerOrderIdentifierType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link TimeIntervalType }
     * 
     */
    public TimeIntervalType createTimeIntervalType() {
        return new TimeIntervalType();
    }

    /**
     * Create an instance of {@link ChoiceBusinessInteractionIdentifierInBillingOrderType }
     * 
     */
    public ChoiceBusinessInteractionIdentifierInBillingOrderType createChoiceBusinessInteractionIdentifierInBillingOrderType() {
        return new ChoiceBusinessInteractionIdentifierInBillingOrderType();
    }

    /**
     * Create an instance of {@link LanguageCodeISOAlpha2Type }
     * 
     */
    public LanguageCodeISOAlpha2Type createLanguageCodeISOAlpha2Type() {
        return new LanguageCodeISOAlpha2Type();
    }

    /**
     * Create an instance of {@link AssignedProductType }
     * 
     */
    public AssignedProductType createAssignedProductType() {
        return new AssignedProductType();
    }

    /**
     * Create an instance of {@link AssignedProductIdentifierType }
     * 
     */
    public AssignedProductIdentifierType createAssignedProductIdentifierType() {
        return new AssignedProductIdentifierType();
    }

    /**
     * Create an instance of {@link SalesChannelIdentifierType }
     * 
     */
    public SalesChannelIdentifierType createSalesChannelIdentifierType() {
        return new SalesChannelIdentifierType();
    }

    /**
     * Create an instance of {@link BillingAccountIdentifierType }
     * 
     */
    public BillingAccountIdentifierType createBillingAccountIdentifierType() {
        return new BillingAccountIdentifierType();
    }

    /**
     * Create an instance of {@link AssignedProductActionCharValType }
     * 
     */
    public AssignedProductActionCharValType createAssignedProductActionCharValType() {
        return new AssignedProductActionCharValType();
    }

    /**
     * Create an instance of {@link ChoiceGeographicLocationIdentifierInProductInventoryType }
     * 
     */
    public ChoiceGeographicLocationIdentifierInProductInventoryType createChoiceGeographicLocationIdentifierInProductInventoryType() {
        return new ChoiceGeographicLocationIdentifierInProductInventoryType();
    }

    /**
     * Create an instance of {@link AssignedPriceElementGroupIdentifierType }
     * 
     */
    public AssignedPriceElementGroupIdentifierType createAssignedPriceElementGroupIdentifierType() {
        return new AssignedPriceElementGroupIdentifierType();
    }

    /**
     * Create an instance of {@link GeographicAddressIdentifierType }
     * 
     */
    public GeographicAddressIdentifierType createGeographicAddressIdentifierType() {
        return new GeographicAddressIdentifierType();
    }

    /**
     * Create an instance of {@link BillingOrderCharValType }
     * 
     */
    public BillingOrderCharValType createBillingOrderCharValType() {
        return new BillingOrderCharValType();
    }

    /**
     * Create an instance of {@link BillingOrderType }
     * 
     */
    public BillingOrderType createBillingOrderType() {
        return new BillingOrderType();
    }

    /**
     * Create an instance of {@link InstallationPointIdentifierType }
     * 
     */
    public InstallationPointIdentifierType createInstallationPointIdentifierType() {
        return new InstallationPointIdentifierType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link ServiceIdentifierType }
     * 
     */
    public ServiceIdentifierType createServiceIdentifierType() {
        return new ServiceIdentifierType();
    }

}
