//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1;
