//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.services.billingordering.flv000624.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bc.web.api.capability.business.b010_02.services.billingordering.flv000624.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponseDataSubmitBillingOrdering_QNAME = new QName("http://api.web.bc/capability/business/b010-02/services/billingordering/flv000624/v1", "ResponseDataSubmitBillingOrdering");
    private final static QName _RequestDataSubmitBillingOrdering_QNAME = new QName("http://api.web.bc/capability/business/b010-02/services/billingordering/flv000624/v1", "RequestDataSubmitBillingOrdering");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bc.web.api.capability.business.b010_02.services.billingordering.flv000624.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseDataSubmitBillingOrderingType }
     * 
     */
    public ResponseDataSubmitBillingOrderingType createResponseDataSubmitBillingOrderingType() {
        return new ResponseDataSubmitBillingOrderingType();
    }

    /**
     * Create an instance of {@link RequestDataSubmitBillingOrderingType }
     * 
     */
    public RequestDataSubmitBillingOrderingType createRequestDataSubmitBillingOrderingType() {
        return new RequestDataSubmitBillingOrderingType();
    }

    /**
     * Create an instance of {@link SubmitBillingOrderingServiceContextRequestType }
     * 
     */
    public SubmitBillingOrderingServiceContextRequestType createSubmitBillingOrderingServiceContextRequestType() {
        return new SubmitBillingOrderingServiceContextRequestType();
    }

    /**
     * Create an instance of {@link SubmitBillingOrderingServiceDataRequestType }
     * 
     */
    public SubmitBillingOrderingServiceDataRequestType createSubmitBillingOrderingServiceDataRequestType() {
        return new SubmitBillingOrderingServiceDataRequestType();
    }

    /**
     * Create an instance of {@link SubmitBillingOrderingServiceContextResponseType }
     * 
     */
    public SubmitBillingOrderingServiceContextResponseType createSubmitBillingOrderingServiceContextResponseType() {
        return new SubmitBillingOrderingServiceContextResponseType();
    }

    /**
     * Create an instance of {@link SubmitBillingOrderingServiceDataResponseType }
     * 
     */
    public SubmitBillingOrderingServiceDataResponseType createSubmitBillingOrderingServiceDataResponseType() {
        return new SubmitBillingOrderingServiceDataResponseType();
    }

    /**
     * Create an instance of {@link SubmitBillingOrderingManagedEntityDeltaResponseType }
     * 
     */
    public SubmitBillingOrderingManagedEntityDeltaResponseType createSubmitBillingOrderingManagedEntityDeltaResponseType() {
        return new SubmitBillingOrderingManagedEntityDeltaResponseType();
    }

    /**
     * Create an instance of {@link ReferenceObjectsType }
     * 
     */
    public ReferenceObjectsType createReferenceObjectsType() {
        return new ReferenceObjectsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseDataSubmitBillingOrderingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.web.bc/capability/business/b010-02/services/billingordering/flv000624/v1", name = "ResponseDataSubmitBillingOrdering")
    public JAXBElement<ResponseDataSubmitBillingOrderingType> createResponseDataSubmitBillingOrdering(ResponseDataSubmitBillingOrderingType value) {
        return new JAXBElement<ResponseDataSubmitBillingOrderingType>(_ResponseDataSubmitBillingOrdering_QNAME, ResponseDataSubmitBillingOrderingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDataSubmitBillingOrderingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.web.bc/capability/business/b010-02/services/billingordering/flv000624/v1", name = "RequestDataSubmitBillingOrdering")
    public JAXBElement<RequestDataSubmitBillingOrderingType> createRequestDataSubmitBillingOrdering(RequestDataSubmitBillingOrderingType value) {
        return new JAXBElement<RequestDataSubmitBillingOrderingType>(_RequestDataSubmitBillingOrdering_QNAME, RequestDataSubmitBillingOrderingType.class, null, value);
    }

}
