//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.services.billingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import bc.web.api.api.schema.servicecontext.processdata.v1.ProcessDataType;


/**
 * <p>Java class for SubmitBillingOrderingServiceContextResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmitBillingOrderingServiceContextResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processData" type="{http://api.web.bc/api/schema/servicecontext/processdata/v1}ProcessDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitBillingOrderingServiceContextResponseType", propOrder = {
    "processData"
})
public class SubmitBillingOrderingServiceContextResponseType {

    @XmlElement(required = true)
    protected ProcessDataType processData;

    /**
     * Gets the value of the processData property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessDataType }
     *     
     */
    public ProcessDataType getProcessData() {
        return processData;
    }

    /**
     * Sets the value of the processData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessDataType }
     *     
     */
    public void setProcessData(ProcessDataType value) {
        this.processData = value;
    }

}
