//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.services.billingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubmitBillingOrderingServiceDataResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmitBillingOrderingServiceDataResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="managedEntityDelta" type="{http://api.web.bc/capability/business/b010-02/services/billingordering/flv000624/v1}SubmitBillingOrderingManagedEntityDeltaResponseType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitBillingOrderingServiceDataResponseType", propOrder = {
    "managedEntityDelta"
})
public class SubmitBillingOrderingServiceDataResponseType {

    @XmlElement(required = true)
    protected SubmitBillingOrderingManagedEntityDeltaResponseType managedEntityDelta;

    /**
     * Gets the value of the managedEntityDelta property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitBillingOrderingManagedEntityDeltaResponseType }
     *     
     */
    public SubmitBillingOrderingManagedEntityDeltaResponseType getManagedEntityDelta() {
        return managedEntityDelta;
    }

    /**
     * Sets the value of the managedEntityDelta property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitBillingOrderingManagedEntityDeltaResponseType }
     *     
     */
    public void setManagedEntityDelta(SubmitBillingOrderingManagedEntityDeltaResponseType value) {
        this.managedEntityDelta = value;
    }

}
