//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.services.billingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1.BillingOrderIdentifierType;
import bc.web.api.capability.business.b010_02.objects.requestsubmitbillingordering.flv000624.v1.BillingOrderType;


/**
 * <p>Java class for SubmitBillingOrderingServiceDataRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmitBillingOrderingServiceDataRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billingOrder" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingOrderType"/>
 *         &lt;element name="billingOrderIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/requestsubmitbillingordering/flv000624/v1}BillingOrderIdentifierType"/>
 *         &lt;element name="referenceObjects" type="{http://api.web.bc/capability/business/b010-02/services/billingordering/flv000624/v1}ReferenceObjectsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitBillingOrderingServiceDataRequestType", propOrder = {
    "billingOrder",
    "billingOrderIdentifier",
    "referenceObjects"
})
public class SubmitBillingOrderingServiceDataRequestType {

    @XmlElement(required = true)
    protected BillingOrderType billingOrder;
    @XmlElement(required = true)
    protected BillingOrderIdentifierType billingOrderIdentifier;
    protected ReferenceObjectsType referenceObjects;

    /**
     * Gets the value of the billingOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BillingOrderType }
     *     
     */
    public BillingOrderType getBillingOrder() {
        return billingOrder;
    }

    /**
     * Sets the value of the billingOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingOrderType }
     *     
     */
    public void setBillingOrder(BillingOrderType value) {
        this.billingOrder = value;
    }

    /**
     * Gets the value of the billingOrderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BillingOrderIdentifierType }
     *     
     */
    public BillingOrderIdentifierType getBillingOrderIdentifier() {
        return billingOrderIdentifier;
    }

    /**
     * Sets the value of the billingOrderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingOrderIdentifierType }
     *     
     */
    public void setBillingOrderIdentifier(BillingOrderIdentifierType value) {
        this.billingOrderIdentifier = value;
    }

    /**
     * Gets the value of the referenceObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceObjectsType }
     *     
     */
    public ReferenceObjectsType getReferenceObjects() {
        return referenceObjects;
    }

    /**
     * Sets the value of the referenceObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceObjectsType }
     *     
     */
    public void setReferenceObjects(ReferenceObjectsType value) {
        this.referenceObjects = value;
    }

}
