//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.capability.business.b010_02.objects.responsesubmitbillingordering.flv000624.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillingOrderRelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillingOrderRelationshipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://api.web.bc/capability/business/b010-02/objects/responsesubmitbillingordering/flv000624/v1}CodeValueType" minOccurs="0"/>
 *         &lt;element name="businessInteractionIdentifier" type="{http://api.web.bc/capability/business/b010-02/objects/responsesubmitbillingordering/flv000624/v1}ChoiceBusinessInteractionIdentifierInBillingOrderType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingOrderRelationshipType", propOrder = {
    "type",
    "businessInteractionIdentifier"
})
public class BillingOrderRelationshipType {

    protected CodeValueType type;
    protected ChoiceBusinessInteractionIdentifierInBillingOrderType businessInteractionIdentifier;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setType(CodeValueType value) {
        this.type = value;
    }

    /**
     * Gets the value of the businessInteractionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ChoiceBusinessInteractionIdentifierInBillingOrderType }
     *     
     */
    public ChoiceBusinessInteractionIdentifierInBillingOrderType getBusinessInteractionIdentifier() {
        return businessInteractionIdentifier;
    }

    /**
     * Sets the value of the businessInteractionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoiceBusinessInteractionIdentifierInBillingOrderType }
     *     
     */
    public void setBusinessInteractionIdentifier(ChoiceBusinessInteractionIdentifierInBillingOrderType value) {
        this.businessInteractionIdentifier = value;
    }

}
