//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.api.schema.servicecontext.processdata.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bc.web.api.api.schema.servicecontext.processdata.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bc.web.api.api.schema.servicecontext.processdata.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CodeValueType }
     * 
     */
    public CodeValueType createCodeValueType() {
        return new CodeValueType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link ProcessDataType }
     * 
     */
    public ProcessDataType createProcessDataType() {
        return new ProcessDataType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link LanguageCodeISOAlpha2Type }
     * 
     */
    public LanguageCodeISOAlpha2Type createLanguageCodeISOAlpha2Type() {
        return new LanguageCodeISOAlpha2Type();
    }

}
