//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.api.schema.servicecontext.processdata.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Include in the ServiceContext section.
 * 
 * <p>Java class for ProcessDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processState" type="{http://api.web.bc/api/schema/servicecontext/processdata/v1}CodeValueType"/>
 *         &lt;element name="processStateReasonId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="processCompletionStatus" type="{http://api.web.bc/api/schema/servicecontext/processdata/v1}CodeValueType"/>
 *         &lt;element name="processCompletionStatusReasonId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="processStepId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessDataType", propOrder = {
    "processId",
    "processState",
    "processStateReasonId",
    "processCompletionStatus",
    "processCompletionStatusReasonId",
    "processStepId"
})
public class ProcessDataType {

    @XmlElement(required = true)
    protected String processId;
    @XmlElement(required = true)
    protected CodeValueType processState;
    protected List<String> processStateReasonId;
    @XmlElement(required = true)
    protected CodeValueType processCompletionStatus;
    protected List<String> processCompletionStatusReasonId;
    protected String processStepId;

    /**
     * Gets the value of the processId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * Sets the value of the processId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessId(String value) {
        this.processId = value;
    }

    /**
     * Gets the value of the processState property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getProcessState() {
        return processState;
    }

    /**
     * Sets the value of the processState property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setProcessState(CodeValueType value) {
        this.processState = value;
    }

    /**
     * Gets the value of the processStateReasonId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processStateReasonId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessStateReasonId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProcessStateReasonId() {
        if (processStateReasonId == null) {
            processStateReasonId = new ArrayList<String>();
        }
        return this.processStateReasonId;
    }

    /**
     * Gets the value of the processCompletionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getProcessCompletionStatus() {
        return processCompletionStatus;
    }

    /**
     * Sets the value of the processCompletionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setProcessCompletionStatus(CodeValueType value) {
        this.processCompletionStatus = value;
    }

    /**
     * Gets the value of the processCompletionStatusReasonId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processCompletionStatusReasonId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessCompletionStatusReasonId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProcessCompletionStatusReasonId() {
        if (processCompletionStatusReasonId == null) {
            processCompletionStatusReasonId = new ArrayList<String>();
        }
        return this.processCompletionStatusReasonId;
    }

    /**
     * Gets the value of the processStepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessStepId() {
        return processStepId;
    }

    /**
     * Sets the value of the processStepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessStepId(String value) {
        this.processStepId = value;
    }

}
