//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.api.schema.commoncontext.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import bc.web.api.api.schema.commoncontext.consumertransaction.v1.ConsumerTransactionType;
import bc.web.api.api.schema.commoncontext.transaction.v1.TransactionType;


/**
 * Contains structure for the CommonContext for a SOAP request
 * 
 * <p>Java class for CommonContextRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonContextRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transaction" type="{http://api.web.bc/api/schema/commoncontext/transaction/v1}TransactionType"/>
 *         &lt;element name="consumerTransaction" type="{http://api.web.bc/api/schema/commoncontext/consumertransaction/v1}ConsumerTransactionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonContextRequestType", propOrder = {
    "transaction",
    "consumerTransaction"
})
public class CommonContextRequestType {

    @XmlElement(required = true)
    protected TransactionType transaction;
    protected ConsumerTransactionType consumerTransaction;

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransaction(TransactionType value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the consumerTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerTransactionType }
     *     
     */
    public ConsumerTransactionType getConsumerTransaction() {
        return consumerTransaction;
    }

    /**
     * Sets the value of the consumerTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerTransactionType }
     *     
     */
    public void setConsumerTransaction(ConsumerTransactionType value) {
        this.consumerTransaction = value;
    }

}
