//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.23 at 12:36:04 PM CET 
//


package bc.web.api.api.schema.commoncontext.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bc.web.api.api.schema.commoncontext.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CommonContextFaultResponse_QNAME = new QName("http://api.web.bc/api/schema/commoncontext/v2", "CommonContextFaultResponse");
    private final static QName _CommonContextRequest_QNAME = new QName("http://api.web.bc/api/schema/commoncontext/v2", "CommonContextRequest");
    private final static QName _CommonContextResponse_QNAME = new QName("http://api.web.bc/api/schema/commoncontext/v2", "CommonContextResponse");
    private final static QName _CommonContextEvent_QNAME = new QName("http://api.web.bc/api/schema/commoncontext/v2", "CommonContextEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bc.web.api.api.schema.commoncontext.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommonContextEventType }
     * 
     */
    public CommonContextEventType createCommonContextEventType() {
        return new CommonContextEventType();
    }

    /**
     * Create an instance of {@link CommonContextRequestType }
     * 
     */
    public CommonContextRequestType createCommonContextRequestType() {
        return new CommonContextRequestType();
    }

    /**
     * Create an instance of {@link CommonContextResponseType }
     * 
     */
    public CommonContextResponseType createCommonContextResponseType() {
        return new CommonContextResponseType();
    }

    /**
     * Create an instance of {@link CommonContextFaultResponseType }
     * 
     */
    public CommonContextFaultResponseType createCommonContextFaultResponseType() {
        return new CommonContextFaultResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonContextFaultResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.web.bc/api/schema/commoncontext/v2", name = "CommonContextFaultResponse")
    public JAXBElement<CommonContextFaultResponseType> createCommonContextFaultResponse(CommonContextFaultResponseType value) {
        return new JAXBElement<CommonContextFaultResponseType>(_CommonContextFaultResponse_QNAME, CommonContextFaultResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonContextRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.web.bc/api/schema/commoncontext/v2", name = "CommonContextRequest")
    public JAXBElement<CommonContextRequestType> createCommonContextRequest(CommonContextRequestType value) {
        return new JAXBElement<CommonContextRequestType>(_CommonContextRequest_QNAME, CommonContextRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonContextResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.web.bc/api/schema/commoncontext/v2", name = "CommonContextResponse")
    public JAXBElement<CommonContextResponseType> createCommonContextResponse(CommonContextResponseType value) {
        return new JAXBElement<CommonContextResponseType>(_CommonContextResponse_QNAME, CommonContextResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonContextEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.web.bc/api/schema/commoncontext/v2", name = "CommonContextEvent")
    public JAXBElement<CommonContextEventType> createCommonContextEvent(CommonContextEventType value) {
        return new JAXBElement<CommonContextEventType>(_CommonContextEvent_QNAME, CommonContextEventType.class, null, value);
    }

}
